### ISSUE TITLE
@import

### ISSUE THREAD

**Issue by mdpenguino** [RafaelDeJongh/MyAnimeList#2]
MAL have been enabling their site again and the list style no longer works due to the use of the @import tags. Is there a solution to this?

**Comment by RafaelDeJongh** [comment]
@mdpenguino 

MAL is far from being proper again, with every change they break something else... this update is the @import.

Currently the only "solution" would be to hard copy the css from this github repo into their own editor. But the reason I used (and many others) @import was because MAL disabled various selectors in their own editor making some elements not render properly.

So a full fix for this definitely not, and to be honest I've really had enough of the slow, unresponsive way they handled this whole situation... it's been two months already!

That said, if at any point in time I might change my opinion on it once they figured out how to actually develop a site properly and maintain it, then I might remake this theme but then with the modern style theme instead of the classic!

I will put this issue on resolved as this is really not something I can't control or fix I am afraid.
